version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'DUS_rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    networks:
      - diagnostic-mysql-network

  app:
    build: .
    container_name: diagnostic_user_service
    ports:
      - 9000:9000
    environment:
      DB_HOST : diagnostic_DB
      DB_PORT : 3307
      DB_NAME : Diagnostic  
      DB_USERNAME : root
      DB_PASSWORD : password
      AMQP_URL: amqp://guest:guest@DUS_rabbitmq:5672
    depends_on:
      - rabbitmq
    volumes:
      - .:/var/www/html
    networks:
      - diagnostic-mysql-network


  mysql:
    image: "mysql"
    container_name: diagnostic_DB
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE : Diagnostic
      MYSQL_ROOT_USER : root
      MYSQL_ROOT_PASSWORD : password
    networks:
      - diagnostic-mysql-network


volumes:
  db_data: {}

networks:
  diagnostic-mysql-network: 
    driver: bridge

